# Generated by Django 5.2 on 2025-10-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
