# Generated by Django 5.2 on 2025-10-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_applicant_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='resume',
        ),
    ]
